export const MENU = {
 INDICE: {
    INDEX: 'INDICE',
    PRODUCTO: {
        URL: 'INDICE/PRODUCTO',
        INDEX: 'PRODUCTO'
    },
    CLIENTE: {
        URL:'INDICE/CLIENTE',
        INDEX: 'CLIENTE'
    },
    PROVEEDOR: {
        URL:'INDICE/PROVEEDOR', 
        INDEX: 'PROVEEDOR'
    },
    CATEGORIAS: {
        URL: 'INDICE/CATEGORIAS',
        INDEX: 'CATEGORIAS'
    },
    MARCAS: {
        URL: 'INDICE/MARCAS',
        INDEX: 'MARCAS'
    },
    MEDICION: {
        URL: 'INDICE/MEDICION',
        INDEX: 'MEDICION'
    },
    USUARIO: {
        URL: 'INDICE/USUARIO',
        INDEX: 'USUARIO'
    },
 },
 PROCESOS: {
    INDEX: 'PROCESOS',
    ENTRADAINVENTARIO: {
        URL: 'PROCESOS/ENTRADAINVENTARIO',
        INDEX: 'ENTRADAINVENTARIO'},
    REIMPRIMIRFACTURAS: {
        URL: 'PROCESOS/REIMPRIMIRFACTURAS',
        INDEX: 'REIMPRIMIRFACTURAS'
    },
    CAJONDINERO: {
        URL: 'PROCESOS/CAJONDINERO', 
        INDEX: 'CAJONDINERO'
    },
    CORTECAJA: {
        URL: 'PROCESOS/CORTECAJA', 
        INDEX: 'CORTECAJA'
    },
 },
 CARTERA: {
    INDEX: 'CARTERAS',
    CUENTASPORCOBRAR: {
        URL: 'CARTERA/CUENTASPORCOBRAR', 
        INDEX: 'CUENTASPORCOBRAR'
    },
    CUENTASPORPAGAR: {
        URL: 'CARTERA/CUENTASPORPAGAR',
        INDEX: 'CUENTASPORPAGAR'
    }
 },
 REPORTES: {
    INDEX: 'REPORTES',
    REPORTEINVENTARIO: {
        URL :'REPORTES/REPORTEINVENTARIO',
        INDEX: 'REPORTEINVENTARIO'
    },
    REPORTECONTABLE: {
        URL: 'REPORTES/REPORTECONTABLE', 
        INDEX: 'REPORTECONTABLE'
    }
 }
}